version: "3.7"
services:
  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    restart: always
    environment:
      - BACKEND_PORT=5000
      - BACKEND_HOST=backend
    ports:
      - 80:3000
      - 443:3000
    networks:
      - default

  database:
    build:
      context: backend
      dockerfile: mysql.dockerfile
    restart: always
    volumes:
      - .mysql:/var/lib/mysql
    ports:
      - 33061:3306
    networks:
      - backend

  backend:
    build:
      context: backend
      dockerfile: java.dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database
    environment:
      - ENTRYPOINT_MYSQL_HOST=database
      - MYSQL_HOST=database:3306
      - MYSQL_DATABASE_NAME=atlas-db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=REDACTED_PROD_PASWORD
      - JWT_KEY=signingkeyshouldbesettedupforaproductionenvironment
      - HMAC_SALT=REDACTED
    networks:
      - default
      - backend

networks:
  default:
    name: general-network
  backend:
    name: backend-network
