FROM openjdk:17-jdk-slim

ADD . /backend
WORKDIR /backend
RUN chmod +x ./mvnw
# clean up crlf endings:
RUN sed -i 's/\r$//' mvnw
# TODO: cache dependencies for faster dev builds. but no need to do it in prod (i guess)
RUN ./mvnw package -DskipTests

EXPOSE 5000

ENTRYPOINT ["java","-jar","target/atlas-0.0.1.jar"]